version: '3'
services:
  nginx:
    build: ./nginx
    depends_on:
      - php
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/www:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/cert:/etc/nginx/cert
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log/error.log:/var/log/nginx/error.log
    networks:
      - frontend
    restart: always
    container_name: nginx

  php:
    build: ./php
    volumes:
      - ./nginx/www:/var/www/html
      - ./php/config/php.ini:/etc/php/7.3/fpm/php.ini
      - ./php/config/php-fpm.conf:/etc/php/7.3/fpm/php-fpm.conf
      - ./php/config/php-fpm.d:/usr/etc/php-fpm.d
      - ./php/service:/opt/service
      - ./php/cron:/etc/cron.d
    networks:
      - frontend
      - backend  
    restart: always
    container_name: php

  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/my.cnf
      - ./nginx/www:/var/www
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - backend
    restart: always
    container_name: mysql

  redis:
    build: ./redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf/:/usr/local/etc/redis.conf
      - ./redis/data:/usr/local/redis/data
      - ./redis/redis.log:/usr/local/redis/redis.log
    networks:
      - backend
    restart: always
    container_name: redis

networks:
  frontend:
  backend:
    
